export type Locale = "en" | "vi" | "zh" | "fr" | "es";
const countryLocales: Record<string, Locale> = { VN: "vi", CN: "zh", TW: "zh", HK: "zh", MO: "zh", FR: "fr", BE: "fr", CA: "fr", CH: "fr", LU: "fr", MC: "fr" };
const messages = {
  en: { allFonts: "All fonts", vietnamese: "Vietnamese fonts", collections: "Collections", home: "Home", explore: "Explore fonts", categories: "Browse categories", liveCatalog: "Live catalog", findType: "Find your type.", searchPlaceholder: "Search by font name or designer…", allStyles: "All styles", vietnameseReady: "Vietnamese ready", vietnameseOnly: "Vietnamese only ✓", preview: "Preview", loadMore: "Load more", noResults: "No typefaces match that search.", fontFamilies: "font families", matching: "matching families · preview before choosing.", newSpecimen: "New specimen →", everyLetter: "Every letter", pointOfView: "has a point of view.", differentFont: "A different font each visit", browseAll: "Browse all fonts →", clearLicenses: "Clear licenses", livePreview: "Live preview", styles: "Styles", footerText: "Preview and explore typefaces through a clearly organized catalog.", licenses: "Licenses", terms: "Terms", privacy: "Privacy" },
  vi: { allFonts: "Tất cả font", vietnamese: "Font tiếng Việt", collections: "Bộ sưu tập", home: "Trang chủ", explore: "Khám phá font", categories: "Xem theo nhóm", liveCatalog: "Thư viện đang có", findType: "Tìm kiểu chữ phù hợp.", searchPlaceholder: "Tìm theo tên font hoặc người thiết kế…", allStyles: "Tất cả kiểu", vietnameseReady: "Có tiếng Việt", vietnameseOnly: "Chỉ font tiếng Việt ✓", preview: "Xem trước", loadMore: "Xem thêm", noResults: "Không tìm thấy font phù hợp.", fontFamilies: "họ font", matching: "họ font phù hợp · xem trước trước khi chọn.", newSpecimen: "Đổi mẫu khác →", everyLetter: "Mỗi con chữ", pointOfView: "đều có một cá tính riêng.", differentFont: "Mỗi lần vào là một font khác", browseAll: "Xem toàn bộ font →", clearLicenses: "Giấy phép rõ ràng", livePreview: "Xem trước trực tiếp", styles: "Kiểu chữ", footerText: "Khám phá và xem trước font trong một thư viện được sắp xếp rõ ràng.", licenses: "Giấy phép", terms: "Điều khoản", privacy: "Riêng tư" },
  zh: { allFonts: "全部字体", vietnamese: "越南语字体", collections: "字体分类", home: "首页", explore: "探索字体", categories: "浏览分类", liveCatalog: "字体目录", findType: "找到合适的字体。", searchPlaceholder: "按字体名称或设计师搜索…", allStyles: "全部风格", vietnameseReady: "支持越南语", vietnameseOnly: "仅看越南语字体 ✓", preview: "预览", loadMore: "加载更多", noResults: "没有找到匹配的字体。", fontFamilies: "个字体家族", matching: "个匹配字体 · 选择前先预览。", newSpecimen: "换一个样本 →", everyLetter: "每个字母", pointOfView: "都有自己的表达。", differentFont: "每次访问显示不同字体", browseAll: "浏览全部字体 →", clearLicenses: "授权清晰", livePreview: "实时预览", styles: "风格", footerText: "在清晰整理的字体目录中预览和探索字体。", licenses: "授权", terms: "条款", privacy: "隐私" },
  fr: { allFonts: "Toutes les polices", vietnamese: "Polices vietnamiennes", collections: "Collections", home: "Accueil", explore: "Explorer les polices", categories: "Parcourir les catégories", liveCatalog: "Catalogue", findType: "Trouvez la bonne police.", searchPlaceholder: "Rechercher par nom ou créateur…", allStyles: "Tous les styles", vietnameseReady: "Vietnamien pris en charge", vietnameseOnly: "Vietnamien uniquement ✓", preview: "Aperçu", loadMore: "Afficher plus", noResults: "Aucune police ne correspond.", fontFamilies: "familles", matching: "familles correspondantes · prévisualisez avant de choisir.", newSpecimen: "Changer de modèle →", everyLetter: "Chaque lettre", pointOfView: "a son propre caractère.", differentFont: "Une police différente à chaque visite", browseAll: "Voir toutes les polices →", clearLicenses: "Licences claires", livePreview: "Aperçu en direct", styles: "Styles", footerText: "Prévisualisez et explorez les polices dans un catalogue bien organisé.", licenses: "Licences", terms: "Conditions", privacy: "Confidentialité" }
  , es: { allFonts: "Todas las fuentes", vietnamese: "Fuentes vietnamitas", collections: "Colecciones", home: "Inicio", explore: "Explorar fuentes", categories: "Ver categorías", liveCatalog: "Catálogo", findType: "Encuentra la fuente adecuada.", searchPlaceholder: "Buscar por nombre o diseñador…", allStyles: "Todos los estilos", vietnameseReady: "Compatible con vietnamita", vietnameseOnly: "Solo fuentes vietnamitas ✓", preview: "Vista previa", loadMore: "Cargar más", noResults: "No se encontraron fuentes.", fontFamilies: "familias tipográficas", matching: "familias encontradas · previsualiza antes de elegir.", newSpecimen: "Cambiar muestra →", everyLetter: "Cada letra", pointOfView: "tiene su propia personalidad.", differentFont: "Una fuente diferente en cada visita", browseAll: "Ver todas las fuentes →", clearLicenses: "Licencias claras", livePreview: "Vista previa en vivo", styles: "Estilos", footerText: "Explora y previsualiza fuentes en un catálogo organizado.", licenses: "Licencias", terms: "Términos", privacy: "Privacidad" }
} as const;
export type Messages = (typeof messages)[Locale];
export function resolveLocale(country?: string | null, acceptLanguage?: string | null, cookie?: string | null): Locale { const forced = cookie?.match(/(?:^|;\s*)bliss_locale=(en|vi|zh|fr)(?:;|$)/)?.[1] as Locale | undefined; if (forced) return forced; if (country && countryLocales[country.toUpperCase()]) return countryLocales[country.toUpperCase()]; for (const part of (acceptLanguage || "").split(",")) { const language = part.trim().split(";", 1)[0].toLowerCase(); if (language.startsWith("vi")) return "vi"; if (language.startsWith("zh")) return "zh"; if (language.startsWith("fr")) return "fr"; if (language.startsWith("en")) return "en"; } return "en"; }
export function getMessages(locale: Locale): Messages { return messages[locale]; }
export const specimenText: Record<Locale, { line: string; detail: string }> = { en: { line: "Every letter", detail: "has a point of view." }, vi: { line: "Mỗi con chữ", detail: "đều có một cá tính riêng." }, zh: { line: "每个字母", detail: "都有自己的表达。" }, fr: { line: "Chaque lettre", detail: "a son propre caractère." }, es: { line: "Cada letra", detail: "tiene su propia personalidad." } };
