"use client";

import { useState } from "react";

export default function BulkImportForm({ onClose }: { onClose: () => void }) {
  const [value, setValue] = useState('[\n  { "name": "Example Font", "category": "DISPLAY", "license": "OFL-1.1" }\n]');
  const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage("Importing..."); try { const payload = JSON.parse(value); const response = await fetch("/api/admin/fonts/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fonts: payload }) }); const data = await response.json(); setMessage(response.ok ? `Imported ${data.inserted} records. Refresh the dashboard.` : data.error || "Import failed."); } catch { setMessage("Invalid JSON. Check the format and try again."); } }
  return <div className="fixed inset-0 z-20 flex items-center justify-center bg-[#18211b]/30 p-5" onClick={onClose}><form onSubmit={submit} className="w-full max-w-2xl rounded-3xl bg-white p-7 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[0.18em] text-[#829087]">Catalog tools</p><h2 className="mt-2 text-3xl font-semibold">Bulk import metadata</h2></div><button type="button" onClick={onClose} className="text-xl text-[#829087]">×</button></div><p className="mt-4 text-sm leading-6 text-[#69756c]">Paste a JSON array. New records are created as drafts and duplicate IDs are skipped by MongoDB.</p><textarea value={value} onChange={(event) => setValue(event.target.value)} className="mt-5 min-h-64 w-full rounded-2xl border border-[#dce3dd] bg-[#fbfcfa] p-4 font-mono text-xs outline-none focus:border-[#5e7965]" spellCheck={false} /><div className="mt-5 flex items-center justify-between gap-4"><span className="text-sm text-[#52745b]">{message}</span><div className="flex gap-3"><button type="button" onClick={onClose} className="rounded-full border border-[#dce3dd] px-5 py-3 text-sm">Close</button><button className="rounded-full bg-[#1d241f] px-5 py-3 text-sm font-medium text-white">Import JSON</button></div></div></form></div>;
}
